name: CAll Build Start UP

on:
  workflow_dispatch:

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - name: Use main workflow
        run: |
          echo "This repository is device-specific."
          echo "Please run: Build Redmi 10X 5G Kernel"
